# Generated by Django 5.2.14 on 2026-05-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='materia',
            field=models.CharField(max_length=50),
        ),
    ]
