# Generated by Django 5.2.14 on 2026-05-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0002_alter_alumno_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='materia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='materiaactividad',
            name='nombre_materias_no_entregadas',
            field=models.CharField(max_length=200),
        ),
    ]
