# Generated by Django 5.2.14 on 2026-05-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0003_alter_alumno_materia_alter_alumno_nombre_completo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnomateria',
            old_name='calificion',
            new_name='calificacion',
        ),
    ]
