# Generated by Django 5.2.14 on 2026-05-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0004_rename_calificion_alumnomateria_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='materia',
        ),
    ]
