# Generated by Django 5.2.14 on 2026-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0005_remove_alumno_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='google_id',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='alumnomateria',
            unique_together={('alumno', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='materiaactividad',
            unique_together={('materia', 'nombre_materias_no_entregadas')},
        ),
    ]
