# Generated by Django 5.2.14 on 2026-05-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0006_alumno_google_id_alter_materia_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='google_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='google_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
