# Generated by Django 5.2.14 on 2026-05-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0007_materia_google_id_alter_alumno_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='google_id',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='google_id',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
    ]
