# Generated by Django 5.2.14 on 2026-05-15 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0008_alter_alumno_google_id_alter_materia_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnomateria',
            name='calificacion',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_entregada', models.BooleanField(default=False)),
                ('calificacion', models.IntegerField(default=0)),
                ('nombre_materias_no_entregadas', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generar_reporte.materia')),
            ],
            options={
                'unique_together': {('materia', 'nombre_materias_no_entregadas')},
            },
        ),
        migrations.DeleteModel(
            name='MateriaActividad',
        ),
    ]
