# Generated by Django 5.2.14 on 2026-05-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0009_remove_alumnomateria_calificacion_actividad_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='actividad',
            name='alumno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='generar_reporte.alumno'),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('alumno', 'materia', 'nombre_materias_no_entregadas')},
        ),
    ]
