# Generated by Django 5.2.14 on 2026-05-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generar_reporte', '0010_alter_actividad_unique_together_actividad_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('google_id', models.CharField(default=0, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generar_reporte.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generar_reporte.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'materia')},
            },
        ),
    ]
